spring:
  profiles:
    active: local
doma:
  dialect: postgres
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
spring:
  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.context.ContextResourceLoaderAutoConfiguration,
      org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration,
      org.springframework.cloud.aws.autoconfigure.cache.ElastiCacheAutoConfiguration,
      org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration,
      org.springframework.cloud.aws.autoconfigure.jdbc.AmazonRdsDatabaseAutoConfiguration,
      org.springframework.cloud.aws.autoconfigure.metrics.CloudWatchExportAutoConfiguration